apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "cloudatlas.fullname" . }}-migrate
  labels:
    app.kubernetes.io/name: {{ include "cloudatlas.name" . }}
    app.kubernetes.io/component: migrate
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: "{{ .Values.image.repository }}-migrate:{{ .Values.image.tag }}"
          env:
            - name: DATABASE_URL
              value: {{ include "cloudatlas.databaseUrl" . | quote }}
